### ISSUE TITLE
Error: Bowtie2 or BEDTools not loaded

### ISSUE THREAD

**Issue by ConYel** [nerettilab/RepEnrich2#13]
Dear RepEnrich team,
I would like to use RepEnrich2 tool.
I have installed everything and I included everything in my $PATH.
I still get this error:

```

File "RepEnrich2_setup.py", line 40
    print "Error: Bowtie2 or BEDTools not loaded"
                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Error: Bowtie2 or BEDTools not loaded")?
```
My version of Bowtie2 is :

`/home/rstudio/Documents/gitstaff/bowtie2-2.3.5.1-linux-x86_64/bowtie2-align-s version 2.3.5.1
64-bit
Built on 
Wed Apr 17 02:50:12 UTC 2019
Compiler: gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 
Options: -O3 -m64 -msse2 -funroll-loops -g3 -g -O2 -fvisibility=hidden -I/hbb_exe_gc_hardened/include -ffunction-sections -fdata-sections -fstack-protector -D_FORTIFY_SOURCE=2 -fPIE -std=c++98 -DPOPCNT_CAPABILITY -DWITH_TBB -DNO_SPINLOCK -DWITH_QUEUELOCK=1
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
`
I tried to find Bowtie2 version 2.2.9 in bioconda but there is only : 

> 2.3.5-0, 2.3.4.3-1, 2.3.4.3-0, 2.3.4.2-0, 2.3.4.1-1, 2.3.4.1-0, 2.3.4-0, 2.3.3.1-0, 2.3.2-1, 2.3.0-1, 

> 2.3.0-0, 2.2.8-2, 2.2.8-1

Is there something I could do?

Thank you in advance,
Con

**Comment by nskvir** [comment]
Hi there, 

Which version of Python are you using?

**Comment by ConYel** [comment]
Python 3.7.2

**Comment by nskvir** [comment]
Ah, that's almost certainly the issue - RepEnrich2 was written with Python 2 (as opposed to Python 3). There are a lot of major syntax differences between the two, so if you try running with a version of Python starting with 2.7.x it should run properly. Apologies if this was ambiguous from the readme!

Best,
Nick

**Comment by ConYel** [comment]
Thank you, I'll test it and let you know!

**Comment by ConYel** [comment]
```
Traceback (most recent call last):
  File "/home/rstudio/Documents/gitstaff/RepEnrich2/RepEnrich2_setup.py", line 8, in <module>
    from Bio import SeqIO
ImportError: No module named Bio
python --version
Python 2.7.15

```
Now this

**Comment by nskvir** [comment]
Yes, it seems like you'd probably have to rerun the setup step and modify the --offrate value in the script to build new indices if that's what you need.  I personally have never done this though, so I can't really say what kind of effects it would have on things like run-time. 

Hope this helps!
-Nick

**Comment by ConYel** [comment]
Thanks!
Last question I hope,
I run the
`RepEnrich2_setup.py`
 setup and it's running for 478 min
`  99.7  9.1 478:48.25 python`
I get :

> `Returning from initFromVector` 
> 
> `Wrote 4488169 bytes to primary EBWT file: /home/rstudio/Documents/Databases/setup_folder_hg38/MamGypLTR3a.rev.1.bt2`
> `Wrote 200944 bytes to secondary EBWT file: /home/rstudio/Documents/Databases/setup_folder_hg38/MamGypLTR3a.rev.2.bt2`
> `Re-opening _in1 and _in2 as input streams
> Returning from Ebwt constructor`
> `Headers:
>     len: 803744
>     bwtLen: 803745
>     sz: 200936
>     bwtSz: 200937
>     lineRate: 6
>     offRate: 4
>     offMask: 0xfffffff0
>     ftabChars: 10
>     eftabLen: 20
>     eftabSz: 80
>     ftabLen: 1048577
>     ftabSz: 4194308
>     offsLen: 50235
>     offsSz: 200940
>     lineSz: 64
>     sideSz: 64
>     sideBwtSz: 48
>     sideBwtLen: 192
>     numSides: 4187
>     numLines: 4187
>     ebwtTotLen: 267968
>     ebwtTotSz: 267968
>     color: 0
>     reverse: 1`
> `Total time for backward call to driver() for mirror index: 00:00:00`
> `processing repgenome AluJr.fa (8350 of 14942)`

Is there a problem with the setup?

**Comment by nskvir** [comment]
Looks like it's running normally to me - as long as it's not throwing any errors and is generating non-empty files in the setup folder I'd just wait for it to finish.

**Comment by ConYel** [comment]
Thanks for everything!!!
