### ISSUE TITLE
RepEnrich2_setup.py

### ISSUE THREAD

**Issue by Danielchan1324** [nerettilab/RepEnrich2#15]
Sorry, can you help me?
when I run the RepEnrich2_setup.py on Ubuntu, this pop up. I dun know how to solve it. Please give me some advice.
![bug](https://user-images.githubusercontent.com/51405124/60434633-29830780-9c3a-11e9-85b6-beff05b148d8.jpg)

**Comment by nskvir** [comment]
Sure, I suspect this happened because there is a slash being added at the end of your setup folder path - try using "ERV/setup_folder_hg19" instead of "ERV/setup_folder_hg19/" and see if that fixes it

-Nick

**Comment by Danielchan1324** [comment]
Thank you Nick! you are right. I ve solved the problem. The RepEnrich2 is still running. Hopefully, it will go well. All the best.
Daniel

**Comment by nskvir** [comment]
No problem!
