### ISSUE TITLE
Keep alignments to metagenome

### ISSUE THREAD

**Issue by adomingues** [nerettilab/RepEnrich2#17]
Hi @nskvir this basically to reboot an issue from [V1](https://github.com/nskvir/RepEnrich/issues/11) because it might have been solved now in `repEnrich2  but I could not find which are the major differences with the previous version.

Basically what I want to know is if this new version keeps the alignments to repeat consensus (which v1 didn't), or if `repConsensus` is still the way to go?

Just as a background, I am working on a project where we want to know if

1. there is change in bulk expression of TE; and 
2. if there is loss/gain of strand bias.

For 2 I definitely need the alignments, therefore the question.

Cheers.

**Comment by nskvir** [comment]
Hi there, 

Apologies for the delayed reply - occasionally the notifications don't show up in my inbox when an issue is posted.  The main difference between version 1 and 2 is a change of aligners used (from Bowtie1 to Bowtie2), but aside from that they behave in the same manner (meaning the alignments to pseudo-genomes are unfortunately not currently preserved).

Best,
Nick
