### ISSUE TITLE
RepEnrich2_setup error

### ISSUE THREAD

**Issue by xiaoyonf** [nerettilab/RepEnrich2#21]
Hi, I tried the command:
python RepEnrich2_setup.py ./hg38_repeatmasker.txt ./hg38.fa ./setup_folder_hg38
But encountered the error:
 File "RepEnrich2_setup.py", line 40
    print "Error: Bowtie2 or BEDTools not loaded"
                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Error: Bowtie2 or BEDTools not loaded")?
I checked my .bash_profile and there are path set up for both tools. 
Can you help me to find anything wrong here?
Thanks
Xiaoyong Fu

**Comment by nskvir** [comment]
Hi Xiaoyong, 
Repenrich was built with Python2.7 but it looks like you might be using Python 3 instead based on the syntax error. Also, be sure you have all the dependencies (like Bowtie2 and Bedtools) installed and loaded prior to the setup.

Let me know if this helps!

**Comment by xiaoyonf** [comment]
Thank you, nskvir. I have now run it successfully in cluster by using python2.7 and other annotated dependences. 
Very best,
Xiaoyong
