### ISSUE TITLE
For non-model organism

### ISSUE THREAD

**Issue by RadPa** [nerettilab/RepEnrich2#23]
Hi,
Can I use RepEnrich2 for the non-model organisms, for example, an invertebrate like Drosophila (not D. melanogaster). 

Thank you

Good Day
Radhika

**Comment by nskvir** [comment]
Hi Radhika, 

As long as you have a reference genome, and can provide annotation for repetitive elements from Repeatmasker (or using a custom bedfile as shown in the tutorial) you should be able to use RepEnrich2 for non-model organisms. 

Best,
Nick

**Comment by RadPa** [comment]
Thank you.

Good Day
Radhika
