### ISSUE TITLE
RepEnrich with different aligner? 

### ISSUE THREAD

**Issue by richardheery** [nerettilab/RepEnrich2#25]
Hi, 

I am wondering can RepEnrich2 work with BAM files from any aligners besides bowtie2 or is it essential that bowtie2 is used for some reason?

**Comment by nskvir** [comment]
Hi there, 

Sorry for the delayed response - you should be able to use RepEnrich2 with other bam files, but it comes with some complications in calling 'uniquely' mapping vs 'multi' mapping reads.  Currently the subset script uses MAPQ values provided from bowtie2 to discern the two types of reads, but most aligners I know of each have their own way of assigning MAPQ scores, which can differ substantially.  If you are familiar enough with how other aligners do this, you can supply a different argument to the Repenrich2_subset.py script (default is 30) to define a different cutoff. 

Best,
Nick
