### ISSUE TITLE
About fasta file 

### ISSUE THREAD

**Issue by Yuanyuan84** [nerettilab/RepEnrich2#7]
Hi

I am a current user of RepEnrich2. 
I was wondering how you get the fasta files, which is the reference database of the bowtie. I know that you record the repeat position in your bed file. what is the relationship between fasta files and bed file(or txt file you provide). 
Thanks for your time

**Comment by nskvir** [comment]
Hi again, 

I'm not sure if you saw the response in the last thread you opened, but I think it should answer your question -

> If you are talking about the fasta file for reference genomes, they should be available from various sources online such as UCSC, Ensembl, or NCBI (and make sure to index it using the command 'bowtie2-build'). If you are referring to the fasta file to use for the run, it should be rna-seq data. The bed file is simply an annotated list of genomic coordinates (chr, start, end) for the features of interest (i.e. repetitive elements).
> 
> Best,
> Nick

If not, feel free to elaborate and I can try to answer from there!
