### ISSUE TITLE
What results use for further analysis

### ISSUE THREAD

**Issue by iramai** [nerettilab/RepEnrich2#8]
Hi !
Maybe this is not the best place to write my dobts, because what I am writing is not an issue with the program.
I followed all the steps, and finally obtained my DE repetitive elements list. Now my question is about interpreting the results list. Do you think that I can work with all differentially expressed repetitive elements (<0.05 pvalue); or do I need to filter results > 2FoldChange and <0.5FoldChange as usually it is done when working with genes?

**Comment by nskvir** [comment]
Hi there, 
Thank you for your interest in our software - the answer to this question is ultimately something that is dependent  on experimental design and sample sizes.  While I would definitely recommend utilizing standard p-value and FDR cutoffs, fold change cutoffs are a little less clear cut.  If the samples have particularly low counts it likely makes more sense to set a higher threshold for fold change, similarly to how you perform differential expression with normal genes.

**Comment by nskvir** [comment]
I would normalize based on the true library size as shown in the example, as opposed to the sum of the counts you get for just the repetitive elements

Best,
Nick
